name: Restrict Issue Status
on:
  issues:
    types: [edited]

jobs:
  restrict_status_change:
    runs-on: ubuntu-latest
    steps:
      - name: Check if user is authorized
        id: check_user
        uses: actions/github-script@v6
        with:
          script: |
            const authorizedUsers = ['mesw-hirata'];
            const issue = context.payload.issue;
            const user = context.payload.sender.login;
            if (authorizedUsers.includes(user) && issue.labels.some(label => label.name === 'Approved')) {
              return { authorized: true };
            }
            return { authorized: false };

      - name: Revert status change
        if: steps.check_user.outputs.authorized == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            const issue_number = context.payload.issue.number;
            await github.issues.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              state: 'open'
            });
